<?php

/**
 * Implements hook_menu().
 */
function overview_menu() {
  $items['admin/config/content/overview'] = array(
    'title' => 'Overview pages',
    'description' => 'Configure overview pages.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('overview_admin_form'),
    'access arguments' => array('administer overview'),
    'file' => 'overview.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function overview_preprocess_html(&$vars) {
  if ($overview = overview_load()) {
    $vars['classes_array'][] = 'overview overview-' . drupal_html_class($overview['url']);
  }
}

/**
 * Implements hook_permission().
 */
function overview_permission() {
  return array(
    'administer overview' => array(
      'title' => t('Administer Overview'),
      'description' => t('Change overview pages per content type.'),
    ),
  );
}

/**
 * Utility function to extract the URL for the current type.
 */
function overview_get_url($type = '') {
  $urls = overview_get_urls();
  return isset($urls[$type]) ? $urls[$type] : FALSE;
}

/**
 * Utility function to get all overview urls.
 */
function overview_get_urls() {
  $urls = &drupal_static(__FUNCTION__, NULL);

  if (!isset($urls)) {
    foreach (variable_get('overview', array()) as $type => $info) {
      if (!isset($info['url']) or empty($info['url'])) {
        continue;
      }

      $urls[$type] = $info['url'];
    }
  }

  return $urls;
}

/**
 * Main function to load current overview page.
 *
 * @return bool returns the current overview info.
 */
function overview_load() {
  $overview = &drupal_static(__FUNCTION__);

  if (isset($overview)) {
    return $overview;
  }

  $overview = FALSE;
  $urls = overview_get_urls();
  if ($key = array_search(current_path(), $urls)) {
    $settings = variable_get('overview', array());
    $overview = $settings[$key];
  }

  return $overview;
}
